# Generated by Django 4.2.30 on 2026-04-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('ICT', 'Information & Communication Technology'), ('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('CY', 'Cyber Security'), ('DM', 'Digital Marketing'), ('GD', 'Graphic Design'), ('NE', 'Network Engineering'), ('WD', 'Web Development')], max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('reg_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
