# Generated by Django 4.2.30 on 2026-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('ICT', 'Information & Communication Technology'), ('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('CY', 'Cyber Security'), ('DM', 'Digital Marketing'), ('GD', 'Graphic Design'), ('NE', 'Network Engineering'), ('WD', 'Web Development')], max_length=100),
        ),
    ]
